import mongoose from 'mongoose';

const jobOrderSchema = new mongoose.Schema({
  jobOrderNumber: {
    type: String,
    required: false, // Auto-generated by pre-save hook
    unique: true,
    trim: true
  },
  vendorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Vendor',
    required: [true, 'Vendor is required']
  },
  jobWorkType: {
    type: String,
    enum: ['Knitting', 'Dyeing', 'Printing', 'Stitching', 'Finishing'],
    required: [true, 'Job work type is required']
  },
  status: {
    type: String,
    enum: ['Sent', 'In-Process', 'Partially Returned', 'Completed', 'Cancelled'],
    default: 'Sent'
  },
  currentLocation: {
    type: String,
    enum: ['Internal Warehouse', 'Vendor'],
    default: 'Vendor'
  },
  materialsIssued: [{
    materialId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Material',
      required: true
    },
    materialType: {
      type: String,
      enum: ['Yarn', 'Grey Fabric', 'Finished Fabric'],
      required: true
    },
    quantity: {
      type: Number,
      required: true,
      min: 0
    },
    unit: {
      type: String,
      enum: ['kg', 'meters', 'pieces'],
      required: true
    },
    issuedDate: {
      type: Date,
      default: Date.now
    }
  }],
  materialsReceived: [{
    materialId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Material',
      required: true
    },
    materialType: {
      type: String,
      enum: ['Yarn', 'Grey Fabric', 'Finished Fabric'],
      required: true
    },
    quantity: {
      type: Number,
      required: true,
      min: 0
    },
    unit: {
      type: String,
      enum: ['kg', 'meters', 'pieces'],
      required: true
    },
    receivedDate: {
      type: Date,
      default: Date.now
    }
  }],
  processLoss: {
    percentage: {
      type: Number,
      default: 0,
      min: 0,
      max: 100
    },
    calculated: {
      type: Boolean,
      default: false
    }
  },
  challanNumber: {
    type: String,
    trim: true
  },
  challanDate: {
    type: Date
  },
  expectedCompletionDate: {
    type: Date
  },
  actualCompletionDate: {
    type: Date
  },
  gstDetails: {
    cgst: {
      type: Number,
      default: 0
    },
    sgst: {
      type: Number,
      default: 0
    },
    igst: {
      type: Number,
      default: 0
    },
    taxRate: {
      type: Number,
      default: 5
    },
    serviceValue: {
      type: Number,
      default: 0
    }
  },
  notes: {
    type: String,
    trim: true
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  qrCode: {
    type: String
  }
}, {
  timestamps: true
});

// Generate job order number before saving
jobOrderSchema.pre('save', async function(next) {
  if (!this.jobOrderNumber) {
    const count = await mongoose.model('JobOrder').countDocuments();
    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    this.jobOrderNumber = `JO-${year}${month}-${String(count + 1).padStart(4, '0')}`;
  }
  next();
});

// Indexes for faster queries
// Note: jobOrderNumber already has unique: true which creates an index
jobOrderSchema.index({ vendorId: 1, status: 1 });
jobOrderSchema.index({ status: 1 });
jobOrderSchema.index({ currentLocation: 1 });

const JobOrder = mongoose.model('JobOrder', jobOrderSchema);

export default JobOrder;

